# Generated by Django 4.1.2 on 2023-01-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('username', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=20)),
                ('arrival_date', models.DateField()),
                ('arrival_time', models.TimeField()),
                ('preferred_transport', models.CharField(max_length=20)),
            ],
        ),
    ]
