# Generated by Django 4.1.2 on 2023-01-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
