# Generated by Django 4.1.2 on 2023-01-01 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userinfo_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='arrival_date',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='arrival_time',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='arrival',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 19, 55, 56, 900213)),
        ),
    ]
